import os

OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")
MEME_DIRECTORY=os.getenv("MEME_DIRECTORY")
ALLOWED_IMAGE_EXTENSIONS=[".jpg", ".jpeg", ".png", ".bmp"]
DB_PATH=os.getenv("DB_PATH")
ANALYZE_EVERY_N_MINUTES=int(os.getenv("ANALYZE_EVERY_N_MINUTES",10))
WEAVIATE_HOST=os.getenv('WEAVIATE_HOST','localhost')
WEAVIATE_PORT=os.getenv('WEAVIATE_PORT',8080)